// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-4JwRN2VUk8AzC1ty53CRYWVTq2bBFRQ',
    appId: '1:297753615249:web:639c5eafc3c54d1fb05830',
    messagingSenderId: '297753615249',
    projectId: 'petcareapp-c0a3f',
    authDomain: 'petcareapp-c0a3f.firebaseapp.com',
    storageBucket: 'petcareapp-c0a3f.appspot.com',
    measurementId: 'G-N1GSMSYKG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgXSt1hdX7UJmF3aTSWD-9hXbNpBnkZDU',
    appId: '1:297753615249:android:831047a8f7c11d6eb05830',
    messagingSenderId: '297753615249',
    projectId: 'petcareapp-c0a3f',
    storageBucket: 'petcareapp-c0a3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnVHGjWCuFVKWe0OWPhyZfclY7DBhB_5g',
    appId: '1:297753615249:ios:288f95be3204a04eb05830',
    messagingSenderId: '297753615249',
    projectId: 'petcareapp-c0a3f',
    storageBucket: 'petcareapp-c0a3f.appspot.com',
    iosBundleId: 'com.example.petCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnVHGjWCuFVKWe0OWPhyZfclY7DBhB_5g',
    appId: '1:297753615249:ios:288f95be3204a04eb05830',
    messagingSenderId: '297753615249',
    projectId: 'petcareapp-c0a3f',
    storageBucket: 'petcareapp-c0a3f.appspot.com',
    iosBundleId: 'com.example.petCareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-4JwRN2VUk8AzC1ty53CRYWVTq2bBFRQ',
    appId: '1:297753615249:web:510c9cbafbcec176b05830',
    messagingSenderId: '297753615249',
    projectId: 'petcareapp-c0a3f',
    authDomain: 'petcareapp-c0a3f.firebaseapp.com',
    storageBucket: 'petcareapp-c0a3f.appspot.com',
    measurementId: 'G-GWQPKDRN65',
  );
}
